### ISSUE TITLE
peakachu crashes with pandas>0.20.3

### ISSUE THREAD

**Issue by dmaticzka** [tbischler/PEAKachu#8]
peakachu throws

`TypeError: reduction operation 'argmax' not allowed for this dtype`

looks connected to https://github.com/pandas-dev/pandas/issues/18021, also seems to be a workaround there

**Comment by tbischler** [comment]
I committed a fix to master, please test.

**Comment by dmaticzka** [comment]
travis should run again. if the tests work we should be okay

**Comment by dmaticzka** [comment]
kk, patch works
